name: Browserstack Testing
on:
  pull_request:
    types: [opened, reopened]
    branches: [master, v*.*.*]
jobs:
  Creating-images-and-testing:
    runs-on: ubuntu-latest
    env:
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        shell: bash
      - run: unzip -qq -o ngrok-stable-linux-amd64.zip
        shell: bash
      - run: ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}
        shell: bash
      - run: ./ngrok http -region=eu -subdomain=sp1764 8002 > ngrok.log &
        shell: bash
      - name: Install composer
        run: composer i
      - run: ./ngrok http -region=eu -subdomain=sp1770 8002 > ngrok.log &
        shell: bash
      - name: Install composer
        run: composer i
      - run: ./ngrok http -region=eu -subdomain=sp1784 8002 > ngrok.log &
        shell: bash
      - name: Install composer
        run: composer i
      - run: ./ngrok http -region=eu -subdomain=sp1786 8002 > ngrok.log &
        shell: bash
      - name: Install composer
        run: composer i

      - name: Install package
        run: npm ci & npx browserslist@latest --update-db

      - name: Building all PS versions, checking Installing / Uninstalling 
        run: |
          make e2eh1764
          make e2eh1770
          make e2eh1784
          make e2eh1786
          
      - name: Install composer
        run: composer i

      - name: 'BrowserStack Testing Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random
        
      - name: 'Installing Browserstack Cypress CLI'
        run: npm install -g browserstack-cypress-cli
        
      - name: 'NPM update'
        run: npm update --force

      - name: 'Exporting required variables and running Browserstack'
        run: |
          export CYPRESS_${{ secrets.SAFERPAY_USERNAME_TEST }}
          export CYPRESS_${{ secrets.SAFERPAY_PASSWORD_TEST }}
          export CYPRESS_${{ secrets.SAFERPAY_CUSTOMER_ID_TEST }}
          export CYPRESS_${{ secrets.SAFERPAY_TERMINAL_ID_TEST }}
          export CYPRESS_${{ secrets.SAFERPAY_MERCHANT_EMAILS_TEST }}
          export CYPRESS_${{ secrets.SAFERPAY_FIELDS_ACCESS_TOKEN_TEST }}
          browserstack-cypress run --sync

      - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
